SELECT USER
FROM DUAL;
--==>> HR

--○ 세 개 이상의 테이블 조인(JOIN)

-- 형식1(SQL 1992 CODE)
SELECT 테이블명1.컬럼명, 테이블명2.컬럼명, 테이블명3.컬럼명
FROM 테이블명1, 테이블명2, 테이블명3
WHERE 테이블명1.컬럼명1 = 테이블명2.컬럼명1
  AND 테이블명2.컬럼명2 = 테이블명3.컬럼명2;
  
-- 형식2(SQL 1999 CODE)
SELECT 테이블명1.컬럼명, 테이블명2.컬럼명, 테이블명3.컬럼명
FROM 테이블명1 JOIN 테이블명2
ON 테이블명1.컬럼명1 = 테이블명2.컬럼명1
                JOIN 테이블명3
                ON 테이블명2.컬럼명2 = 테이블명3.컬럼명2;


--○ HR 계정 소유 테이블 또는 뷰 목록 조회
SELECT *
FROM TAB;
--==>>
/*
COUNTRIES	        TABLE	
DEPARTMENTS	        TABLE	
EMPLOYEES	        TABLE	
EMP_DETAILS_VIEW	VIEW	
JOBS	            TABLE	
JOB_HISTORY	        TABLE	
LOCATIONS	        TABLE	
REGIONS	            TABLE	
*/


--○ HR.JOBS, HR.EMPLOYEES, HR.DEPARTMENTS 테이블을 대상으로
--   직원들의 정보를 FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME 
--   항목을 조회한다.

SELECT COUNT(*)  
FROM EMPLOYEES;  --> 제일 큰 값이므로 첫 조건절(상위)에 있어야 함
--==>> 107

SELECT *
FROM JOBS;

SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;
--
--① SQL 1992 CODE
  
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
WHERE E.JOB_ID = J.JOB_ID
  AND E.DEPARTMENT_ID = D.DEPARTMENT_ID(+);
  --==>> (+) 를 붙여야 됨,,,, 안붙이면 106개 나온다.....


--② SQL 1999 CODE

--유동언니꺼 ㅡㅠㅠ 지금은 2번 문제 풀자
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME
FROM JOBS J JOIN EMPLOYEES E
ON J.JOB_ID = E.JOB_ID
            LEFT JOIN DEPARTMENTS D
            ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 정답.... 위에 것과 비교해보기
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
   JOIN JOBS J
   ON E.JOB_ID = J.JOB_ID;



--○ EMPLOYEES, DEPARTMENTS, JOBS, LOCATIONS, COUNTRIES, REGIONS 테이블을 대상으로
--   직원들의 정보를 다음과 같이 조회한다.
--   FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_NAME,  --   , CITY, COUNTRY_NAME, REGION_NAME
--      E           E           J           D
컬럼명 알파벳 (알파벳 컬럼명) 포함

SELECT *
FROM EMPLOYEES;     DEPARTMENT_ID A // JOB_ID A

SELECT *            A DEPARTMENT_ID //   LOCATION_ID B
FROM DEPARTMENTS;  

SELECT *            A JOB_ID
FROM JOBS;

SELECT *            B LOCATION_ID // C COUNTRY_ID
FROM LOCATIONS;

SELECT *
FROM COUNTRIES;      COUNTRY_ID  C     // D REGION_ID

SELECT *
FROM REGIONS;       REGOIN_ID   D

SELECT COUNT(*)
FROM EMPLOYEES;
--==>> 107


-- ① 1992
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME
     , L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J, LOCATIONS L, COUNTRIES C, REGIONS R
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND D.LOCATION_ID = L.LOCATION_ID
  AND E.JOB_ID =  J.JOB_ID
  AND C.COUNTRY_ID = L.COUNTRY_ID 
  AND R.REGION_ID = C.REGION_ID;

--◆ 강사님 풀이

--○ 방법1. SQL 1992 CODE
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME, L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM EMPLOYEES E, JOBS J, DEPARTMENTS D, LOCATIONS L, COUNTRIES C,  REGIONS R
WHERE E.JOB_ID =  J.JOB_ID
  AND E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
  AND D.LOCATION_ID = L.LOCATION_ID(+)
  AND L.COUNTRY_ID = C.COUNTRY_ID(+)
  AND C.REGION_ID  = R.REGION_ID(+);  


--○ 방법2. SQL 1999 CODE
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE, D.DEPARTMENT_NAME, L.CITY, C.COUNTRY_NAME, R.REGION_NAME
FROM EMPLOYEES E LEFT JOIN JOBS J 
ON E.JOB_ID =  J.JOB_ID
        LEFT JOIN DEPARTMENTS D
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
                    LEFT JOIN LOCATIONS L
                    ON D.LOCATION_ID = L.LOCATION_ID
                           LEFT JOIN COUNTRIES C
                           ON L.COUNTRY_ID = C.COUNTRY_ID
                                  LEFT JOIN REGIONS R
                                  ON C.REGION_ID  = R.REGION_ID;  
















